[build]
  command = "TZ=Asia/Seoul date '+%Y년 %m월 %d일 %H:%M' > deploy-time.txt"
  publish = "."

[[headers]]
  for = "/stems/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
